vim.g.mapleader = " "

vim.opt.signcolumn = "yes"
vim.opt.relativenumber = true
vim.opt.number = true
vim.opt.wrap = false
vim.opt.scrolloff = 8
vim.opt.sidescrolloff = 8
vim.opt.expandtab = true
vim.opt.cursorline = true
vim.opt.guicursor = "a:block,i:blinkwait700-blinkoff400-blinkon250-block"
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.smartindent = true
vim.opt.updatetime = 100
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.autoread = true
vim.opt.inccommand = "nosplit"
vim.opt.undofile = true
vim.opt.winborder = "solid"
vim.opt.spelllang = { "en_us", "en_gb" }
vim.opt.spelloptions = "camel"
vim.opt.termguicolors = true

vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
vim.opt.foldlevel = 99
vim.opt.foldlevelstart = 99
